#!/bin/bash
# Re-featurise France on the ORIGINAL candidate pairs (reconstructed from the original feat_test* parts, which carry
# the blocking columns), since work/pairs_test.parquet was regenerated by an external run and differs.
set -euo pipefail
cd /home2/home/amritanshu_t/amazon-mlc-26/run
PY=$(pwd)/../venv/bin/python; export PYTHONHASHSEED=0
log() { echo "[$(date +%T)] $*"; }
cd fx2
rm -rf work/feat_testfr work/feat_testfr_dense
log "original France pairs from feature parts"
$PY -c "
import polars as pl, glob
s1 = pl.read_parquet('work/test_s1.parquet', columns=['entity_id','country']).filter(pl.col('country')=='France').select((pl.col('entity_id').str.slice(3).cast(pl.Int64)+10_000_000_000).alias('s1'))
B = ['bscore','nkeys','brank','t_ns1','t_best','t_rank','t_bbest','t_brank','rs','rrank','npool','wmax'] + [f'w{k}' for k in range(8)]
for src, dst in [('../work/feat_test', 'work/pairs_testfr.parquet'), ('../work/feat_test_dense', 'work/pairs_testfr_dense.parquet')]:
    d = pl.concat([pl.read_parquet(p, columns=['s1','t']+B) for p in sorted(glob.glob(src + '/part_*.parquet'))]).join(s1, on='s1')
    d.write_parquet(dst); print(dst, len(d), 'dup pairs', len(d) - d.select('s1','t').n_unique())
"
log "features (blocking pairs)"
for ((w=0; w<4; w++)); do NOFILTER=1 PTAG=testfr POLARS_MAX_THREADS=6 $PY work/build_feats_all.py test 0 work/feat_testfr $w 4 > ../logs2/frnorm2r_feat_$w.log 2>&1 & done; wait
log "features (dense pairs)"
for ((w=0; w<4; w++)); do NOFILTER=1 PTAG=testfr_dense POLARS_MAX_THREADS=6 $PY work/build_feats_all.py test 0 work/feat_testfr_dense $w 4 > ../logs2/frnorm2r_featd_$w.log 2>&1 & done; wait
log "tree model on France pairs"
TAG=dense_s1 TH=0.7 EXCL=1 OUT=out_fr FEAT=work/feat_testfr,work/feat_testfr_dense EXTRA_PAIRFEATS=work/dense/pairfeats_test.parquet POLARS_MAX_THREADS=24 $PY work/predict_test.py > ../logs2/frnorm2_predict.log 2>&1
tail -2 ../logs2/frnorm2_predict.log
log done
